# -*- coding: utf-8 -*-
"""youtube_chat_bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mMTRLvFWJj3-k5ypFPW1_vTb81g2_H7
"""

import os

!pip install -U mistralai

from google.colab import userdata

api_key = userdata.get("MISTRAL_API_KEY")

os.environ["MISTRAL_API_KEY"] = "sk-xxxxxxxxxxxxxxxx"

!pip install -q youtube-transcript-api langchain-community langchain-mistralai faiss-cpu python-dotenv



"""### Explanation of the `pip` Dependency Conflicts

The `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed...` message indicates that `pip` found incompatibilities between the versions of certain packages required by your environment.

Specifically:
*   **`google-colab` (core Colab library) requires `requests==2.32.4`**, but your environment has `requests 2.34.2`.
*   **`google-adk` requires `opentelemetry-api<1.39.0,>=1.36.0`**, but your environment has `opentelemetry-api 1.39.1`.

These conflicts arise because Colab comes with a base set of packages that have specific version requirements. When you install new libraries (like `langchain-community` or `mistralai`), they might depend on newer versions of common libraries like `requests` or `opentelemetry-api`, creating a conflict with the older versions required by Colab's built-in components.

Although these are labeled as `ERROR`, they are often treated as warnings that allow the installation of your requested packages to proceed. However, they indicate that the conflicting pre-installed packages (`google-colab`, `google-adk`) might not function correctly if their features that rely on the specific older dependency versions are used.

### Potential Solution for Dependency Conflicts

The packages you explicitly requested should have installed. If you want to try and resolve these warnings, you can try upgrading `pip` and then reinstalling with a newer dependency resolver. However, be aware that fully resolving these kinds of conflicts in Colab can sometimes be tricky due to the tightly controlled base environment, and sometimes it's best to proceed if your core functionality is working and you don't rely on the specific conflicting parts of `google-colab` or `google-adk`.
"""

# Optional: Upgrade pip to the latest version
!pip install --upgrade pip

# Re-install the packages using the new resolver feature
# This might help in finding a more compatible set of dependencies or provide clearer error messages.
# Note: This will re-run the installation for the specified packages.
!pip install --use-feature=2020-resolver youtube-transcript-api langchain-community langchain-mistralai faiss-cpu python-dotenv

print("Please review the output of the above cell. If dependency warnings still persist but your intended libraries are working, you can generally proceed.")

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_mistralai import ChatMistralAI, MistralAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate

"""**Step 1 : Indexing( document ingestion
)
**
"""

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled

video_id = "0VBKYVDhtbw"

try:
    ytt_api = YouTubeTranscriptApi()

    transcript_list = ytt_api.fetch(video_id)
    transcript = " ".join(
        chunk.text for chunk in transcript_list
    )

    print(transcript)

except TranscriptsDisabled:
    print("Transcript is disabled for this video.")

"""**Text Splitter**"""

splitter= RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)

chunks =splitter.create_documents([transcript])

len(chunks)



from langchain_mistralai import MistralAIEmbeddings
from dotenv import load_dotenv
import os
load_dotenv()

mistral_embeddings= MistralAIEmbeddings(
    api_key=api_key,
    model="mistral-embed"
)

vector_store=FAISS.from_documents(chunks, mistral_embeddings)

vector_store.index_to_docstore_id

vector_store.get_by_ids(['6b96a20b-049e-4e9f-801a-37e7de215215'])

retriever=vector_store.as_retriever(search_type='similarity', search_kwargs={'k':4})

retriever

retriever.invoke("who is  islam makhachev")

from google.colab import userdata
from langchain_mistralai import ChatMistralAI

MISTRAL_API_KEY = userdata.get("MISTRAL_API_KEY")
llm = ChatMistralAI(
    model="mistral-small-latest",
    api_key=MISTRAL_API_KEY,
    temperature=2
)

prompt=PromptTemplate(
    template='''
      you are a helpful assistant answer only from the provided transcript context.
      if the cintext in unsufficient just say don't know.
      {context}
      question: {question}
    ''',
    input_variables=['context', 'question']
)

questions1="tell me in this transcript which two people taking about and what"
retrieved_doc=retriever.invoke(questions1)

final_prompt=prompt.invoke({"context":retrieved_doc, "question":questions1})

answer=llm.invoke(final_prompt)
print(answer)

# we are going to build a chain

from langchain_core.runnables import (
    RunnableParallel,
    RunnablePassthrough,
    RunnableLambda,
)
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

def format_docs(retrieved_doc):
  constex_text="\n\n".join(doc.page_content for doc in retrieved_doc)
  return constex_text

parallel_chain=RunnableParallel(
    context=retriever|RunnableLambda(format_docs),
    question=RunnablePassthrough()
)

parallel_chain.invoke('who is islam makhachev')

parser= StrOutputParser()
main_chain=parallel_chain|prompt|llm|parser

main_chain.invoke("can you summerize this podcast for me ")

